gateway:
  ip: 192.168.87.93

eureka.client.serviceUrl.defaultZone: http://test:${myEureka.password}@localhost:8010/eureka
myEureka.password: "{cipher}9caa4efa30570c73a6b14e7bb4f9993ced460dad3577a6361c5108e99fdffbd0"

api.login.url.path: /photo-user-service/users/login
api.signup.url.path: /photo-user-service/users
api.h2console.url.path: /photo-user-service/h2-console/**

authorization.token.header.name: Authorization
authorization.token.header.prefix: Bearer
authorization.token.secret: kybm8r4sv34lkjh87sknbxm3c999
authorization.token.expirationIntervalMillis: 555555555

albums.url: http://albums-ws/users/%s/albums
albums.exceptions.not-found.text: For this user albums are not found
