gateway:
  ip: 192.168.87.93

authorization.token.header.name: Authorization
authorization.token.header.prefix: Bearer

albums.url: http://albums-ws/users/%s/albums
albums.exceptions.not-found.text: For this user albums are not found
